version: '3'
services:
  scraper:
    build: ./docker
    environment:
      - DB_URI=${DB_URI}
      - PROXY_LIST=${PROXY_LIST}
      - HUNTER_API_KEY=${HUNTER_API_KEY}
      - CAPTCHA_API_KEY=${CAPTCHA_API_KEY}
    volumes:
      - .:/app
    restart: always 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: leads
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: